[package]
name = "catalyst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10"
log = "0.4"
wgpu = "0.18"
glfw = "0.55.0"
pollster = "0.3.0"
